set_device -name GW2A-18 -device_version NA GW2A-LV18QN88C8/I7
set_option -include_path "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/temp_gowin"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_adder.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree0.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree1.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree2.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree3.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree4.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree5.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class0_tree6.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_adder.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree0.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree1.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree2.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree3.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree4.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree5.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/class1_tree6.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/TreeLUT.v"
add_file -type verilog "C:/Users/Guilherme/Desktop/automacao_sintese_gowin/Adult_original/1_w_feature_3_w_tree_3_quat_True_arg_True/TreeLUT/verilog/top_wrapper.v"
set_option -top_module top_wrapper
run all
