-d C:\Users\Guilherme\Desktop\aaa\Covtype\0_w_feature_1_w_tree_5_quat_False_arg_False\temp_gowin\impl\gwsynthesis\project.vg
-p GW2A-18-QFN88-8
-pn GW2A-LV18QN88C8/I7
-cfg C:\Users\Guilherme\Desktop\aaa\Covtype\0_w_feature_1_w_tree_5_quat_False_arg_False\temp_gowin\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
